// xlibdir.C -- generated automatically from `xlibdir.txt'.
"\n"
"\n"
"tmp=${TMPDIR-/tmp}/xc$$\n"
"\n"
"export tmp\n"
"\n"
"mkdir $tmp\n"
"trap \"cd /; rm -fr $tmp; exit 2\" 1 2 15\n"
"cd $tmp\n"
"\n"
"cat <<EOF > Imakefile\n"
"findx:\n"
"	@echo \\${LIBDIR}\n"
"EOF\n"
"\n"
"xmkmf > /dev/null      2> /dev/null\n"
"make findx             2> /dev/null\n"
"\n"
"cd /\n"
"rm -fr $tmp            2> /dev/null\n"
"\n"
"rm -f $tmp/* $tmp/.??* 2> /dev/null\n"
"rmdir $tmp             2> /dev/null\n"
"\n"
"exit 0\n"
